/** slack_event_logs.event_type */
export const SLACK_EVENT = {
  DM_SENT: 'DM_SENT',
  DM_SEND_FAILED: 'DM_SEND_FAILED',
  DM_UPDATED: 'DM_UPDATED',
  DM_UPDATE_FAILED: 'DM_UPDATE_FAILED',
  DM_REMINDER: 'DM_REMINDER',
  DM_REMINDER_FAILED: 'DM_REMINDER_FAILED',
  MODAL_OPENED: 'MODAL_OPENED',
  MODAL_OPEN_FAILED: 'MODAL_OPEN_FAILED',
  MODAL_UPDATED: 'MODAL_UPDATED',
  MODAL_UPDATE_FAILED: 'MODAL_UPDATE_FAILED',
  ACTION_QUEUED: 'ACTION_QUEUED',
  ACTION_VALIDATION_FAILED: 'ACTION_VALIDATION_FAILED',
  REQUESTER_DM_SENT: 'REQUESTER_DM_SENT',
  REQUESTER_DM_FAILED: 'REQUESTER_DM_FAILED',
  REQUESTER_DM_SKIPPED: 'REQUESTER_DM_SKIPPED',
};

/** slack_event_logs.event_status */
export const SLACK_EVENT_STATUS = {
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  PENDING: 'PENDING',
  SKIPPED: 'SKIPPED',
};
